spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:postgresql://localhost:5482/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

# Criar banco automatico
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update, none, create-drop



