server:
  port: 54923
spring:
  application:
    name: libraryapi
  output:
    ansi:
      enabled: ALWAYS #HABILITAR CORES NO CONSOLE
  datasource:
    url: jdbc:postgresql://localhost:5482/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
     show-sql: true
     hibernate:
      ddl-auto: none
     properties:
       hibernate.format_sql: true
  security:
    user:
      name: admin
      password: admin123
      roles: USER
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
springdoc:
  override-with-generic-response: false
logging:
  pattern: #define o padr√£o dos logs
    console: "%clr(%d{dd/MM/yyyy HH:mm:ss.SSS}){faint} %clr([%-5level]){%highlight} %clr([%thread]){magenta} %clr(%logger{36}){cyan} %clr(-){faint} %msg %clr(|){faint} %clr(host=%property{HOSTNAME:-desconhecido}){yellow} %clr(|){faint} %clr(amb=%property{AMBIENTE:-prod}){yellow} %clr(|){faint} %clr(app=%property{spring.application.name:-app}){yellow} %clr(|){faint} %clr(servico=%property{SERVICO:-api}){yellow} %clr(|){faint} %clr(traceId=%X{traceId:-sem_trace}){green} %clr(spanId=%X{spanId:-sem_span}){green} %clr(|){faint} %clr(usuario=%X{usuario:-anon}){blue} %clr(|){faint} %clr(ip=%X{ip:-0.0.0.0}){blue} %clr(|){faint} %clr(reqId=%X{requestId:-sem_req}){green} %clr(|){faint} %clr(status=%X{status:-n/a}){yellow} %clr(|){faint} %clr(tenant=%X{tenant:-n/a}){yellow}%n%wEx"
  file:
    name: app.log
  level:
    root: warn
    # trace
    # debug
    # info
    # warn
    # error
    io:
      github:
        kaiocandido: trace
    org:
      springframework:
        web: debug

# Criar banco automatico
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update, none, create-drop



